// mockNotifications.ts — Mock notification data for Phase 8 development.
// ⚠️ HIPAA: All patient names and appointment data are fictional.

import type {
  NotificationSettings,
  MessageTemplate,
  PatientNotificationPrefs,
  NotificationLog,
} from '../types/notification';

// ── Clinic-level notification settings ────────────────────────────────────
export const MOCK_NOTIFICATION_SETTINGS: NotificationSettings = {
  clinicId: 'clinic-1',
  smsEnabled: true,
  emailEnabled: true,
  senderName: 'Air Dental',
  replyToEmail: 'appointments@airdental.com',
  clinicPhone: '(617) 555-0100',
  timezone: 'America/New_York',
  updatedAt: '2026-03-01T00:00:00Z',
  reminderSchedule: [
    { id: 'rule-1', hoursBeforeAppointment: 72, label: '72 hours before', sendSms: false, sendEmail: true,  enabled: true },
    { id: 'rule-2', hoursBeforeAppointment: 24, label: '24 hours before', sendSms: true,  sendEmail: true,  enabled: true },
    { id: 'rule-3', hoursBeforeAppointment: 2,  label: '2 hours before',  sendSms: true,  sendEmail: false, enabled: true },
  ],
};

// ── Message templates ──────────────────────────────────────────────────────
export const MOCK_TEMPLATES: MessageTemplate[] = [
  {
    id: 'tmpl-sms-1',
    clinicId: 'clinic-1',
    type: 'SMS',
    body: 'Hi {patient_name}! This is a reminder from {clinic_name} that you have an appointment on {date} at {time} with {provider}. Questions? Call us at {clinic_phone}. Reply STOP to opt out.',
    updatedAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'tmpl-email-1',
    clinicId: 'clinic-1',
    type: 'EMAIL',
    subject: 'Appointment Reminder — {clinic_name}',
    body: `<div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:24px;background:#f8fafc;border-radius:12px">
  <h2 style="color:#0f172a;margin-bottom:8px">Appointment Reminder</h2>
  <p style="color:#64748b;font-size:15px">Hi <strong>{patient_name}</strong>,</p>
  <p style="color:#64748b;font-size:15px">This is a friendly reminder of your upcoming appointment:</p>
  <div style="background:white;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:16px 0">
    <p style="margin:4px 0;color:#0f172a"><strong>Date:</strong> {date}</p>
    <p style="margin:4px 0;color:#0f172a"><strong>Time:</strong> {time}</p>
    <p style="margin:4px 0;color:#0f172a"><strong>Provider:</strong> {provider}</p>
    <p style="margin:4px 0;color:#0f172a"><strong>Location:</strong> {clinic_name}</p>
  </div>
  <p style="color:#64748b;font-size:14px">Questions? Call us at <strong>{clinic_phone}</strong>.</p>
  <p style="color:#94a3b8;font-size:12px;margin-top:24px">To unsubscribe from these reminders, reply STOP to any SMS or contact our office.</p>
</div>`,
    updatedAt: '2026-03-01T00:00:00Z',
  },
];

// ── Patient preferences ────────────────────────────────────────────────────
export const MOCK_PATIENT_PREFS: PatientNotificationPrefs[] = [
  { patientId: 'pat-1', smsOptIn: true,  emailOptIn: true,  preferredMethod: 'BOTH' },
  { patientId: 'pat-2', smsOptIn: true,  emailOptIn: true,  preferredMethod: 'EMAIL' },
  { patientId: 'pat-3', smsOptIn: true,  emailOptIn: false, preferredMethod: 'SMS' },
  { patientId: 'pat-4', smsOptIn: false, emailOptIn: true,  preferredMethod: 'EMAIL' },
  { patientId: 'pat-5', smsOptIn: true,  emailOptIn: true,  preferredMethod: 'BOTH' },
  { patientId: 'pat-6', smsOptIn: false, emailOptIn: false, preferredMethod: 'EMAIL', optOutTimestamp: '2026-01-15T10:00:00Z', optOutSource: 'manual' },
  { patientId: 'pat-7', smsOptIn: true,  emailOptIn: true,  preferredMethod: 'SMS' },
  { patientId: 'pat-8', smsOptIn: true,  emailOptIn: true,  preferredMethod: 'BOTH' },
  { patientId: 'pat-9', smsOptIn: false, emailOptIn: true,  preferredMethod: 'EMAIL' },
];

export const MOCK_PATIENT_PREFS_MAP: Record<string, PatientNotificationPrefs> = Object.fromEntries(
  MOCK_PATIENT_PREFS.map(p => [p.patientId, p]),
);

// ── Notification logs ──────────────────────────────────────────────────────
export const MOCK_NOTIFICATION_LOGS: NotificationLog[] = [
  // ── John Smith (pat-1), apt-1: Crown Prep 2026-03-30 09:00 with Dr. Sarah Chen ──
  {
    id: 'notif-1',
    patientId: 'pat-1',
    patientName: 'John Smith',
    appointmentId: 'apt-1',
    appointmentDate: '2026-03-30',
    appointmentTime: '09:00',
    type: 'EMAIL',
    messageContent: 'Hi John Smith, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 9:00 AM | Provider: Dr. Sarah Chen | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'delivered',
    providerResponseId: 'sg-msg-00001',
    sentAt: '2026-03-27T09:00:00Z',
    deliveredAt: '2026-03-27T09:00:15Z',
    retryCount: 0,
    ruleId: 'rule-1',
  },
  {
    id: 'notif-2',
    patientId: 'pat-1',
    patientName: 'John Smith',
    appointmentId: 'apt-1',
    appointmentDate: '2026-03-30',
    appointmentTime: '09:00',
    type: 'SMS',
    messageContent: 'Hi John Smith! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 9:00 AM with Dr. Sarah Chen. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'delivered',
    providerResponseId: 'SM00002aabbccdd',
    sentAt: '2026-03-29T09:00:00Z',
    deliveredAt: '2026-03-29T09:00:22Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  {
    id: 'notif-3',
    patientId: 'pat-1',
    patientName: 'John Smith',
    appointmentId: 'apt-1',
    appointmentDate: '2026-03-30',
    appointmentTime: '09:00',
    type: 'EMAIL',
    messageContent: 'Hi John Smith, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 9:00 AM | Provider: Dr. Sarah Chen | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'delivered',
    providerResponseId: 'sg-msg-00003',
    sentAt: '2026-03-29T09:00:00Z',
    deliveredAt: '2026-03-29T09:00:18Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  {
    id: 'notif-4',
    patientId: 'pat-1',
    patientName: 'John Smith',
    appointmentId: 'apt-1',
    appointmentDate: '2026-03-30',
    appointmentTime: '09:00',
    type: 'SMS',
    messageContent: 'Hi John Smith! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 9:00 AM with Dr. Sarah Chen. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'queued',
    retryCount: 0,
    ruleId: 'rule-3',
  },
  // ── Emma Johnson (pat-2), apt-2: Routine Cleaning 2026-03-30 11:00 with Dr. Sarah Chen ──
  {
    id: 'notif-5',
    patientId: 'pat-2',
    patientName: 'Emma Johnson',
    appointmentId: 'apt-2',
    appointmentDate: '2026-03-30',
    appointmentTime: '11:00',
    type: 'EMAIL',
    messageContent: 'Hi Emma Johnson, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 11:00 AM | Provider: Dr. Sarah Chen | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'delivered',
    providerResponseId: 'sg-msg-00005',
    sentAt: '2026-03-27T11:00:00Z',
    deliveredAt: '2026-03-27T11:00:12Z',
    retryCount: 0,
    ruleId: 'rule-1',
  },
  {
    id: 'notif-6',
    patientId: 'pat-2',
    patientName: 'Emma Johnson',
    appointmentId: 'apt-2',
    appointmentDate: '2026-03-30',
    appointmentTime: '11:00',
    type: 'SMS',
    messageContent: 'Hi Emma Johnson! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 11:00 AM with Dr. Sarah Chen. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'failed',
    errorMessage: 'Invalid phone number format',
    sentAt: '2026-03-29T11:00:00Z',
    retryCount: 2,
    ruleId: 'rule-2',
  },
  {
    id: 'notif-7',
    patientId: 'pat-2',
    patientName: 'Emma Johnson',
    appointmentId: 'apt-2',
    appointmentDate: '2026-03-30',
    appointmentTime: '11:00',
    type: 'EMAIL',
    messageContent: 'Hi Emma Johnson, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 11:00 AM | Provider: Dr. Sarah Chen | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'delivered',
    providerResponseId: 'sg-msg-00007',
    sentAt: '2026-03-29T11:00:00Z',
    deliveredAt: '2026-03-29T11:00:09Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  // ── Michael Brown (pat-3), apt-3: Root Canal 2026-03-30 08:00 with Dr. Michael Torres ──
  {
    id: 'notif-8',
    patientId: 'pat-3',
    patientName: 'Michael Brown',
    appointmentId: 'apt-3',
    appointmentDate: '2026-03-30',
    appointmentTime: '08:00',
    type: 'SMS',
    messageContent: 'Hi Michael Brown! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 8:00 AM with Dr. Michael Torres. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'delivered',
    providerResponseId: 'SM00008eeffgghh',
    sentAt: '2026-03-27T08:00:00Z',
    deliveredAt: '2026-03-27T08:00:31Z',
    retryCount: 0,
    ruleId: 'rule-1',
  },
  {
    id: 'notif-9',
    patientId: 'pat-3',
    patientName: 'Michael Brown',
    appointmentId: 'apt-3',
    appointmentDate: '2026-03-30',
    appointmentTime: '08:00',
    type: 'SMS',
    messageContent: 'Hi Michael Brown! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 8:00 AM with Dr. Michael Torres. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'delivered',
    providerResponseId: 'SM00009iijjkkll',
    sentAt: '2026-03-29T08:00:00Z',
    deliveredAt: '2026-03-29T08:00:19Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  // ── Sophia Davis (pat-4), apt-4: Teeth Whitening 2026-03-30 14:00 with Dr. Michael Torres ──
  {
    id: 'notif-10',
    patientId: 'pat-4',
    patientName: 'Sophia Davis',
    appointmentId: 'apt-4',
    appointmentDate: '2026-03-30',
    appointmentTime: '14:00',
    type: 'EMAIL',
    messageContent: 'Hi Sophia Davis, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 2:00 PM | Provider: Dr. Michael Torres | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'delivered',
    providerResponseId: 'sg-msg-00010',
    sentAt: '2026-03-27T14:00:00Z',
    deliveredAt: '2026-03-27T14:00:08Z',
    retryCount: 0,
    ruleId: 'rule-1',
  },
  {
    id: 'notif-11',
    patientId: 'pat-4',
    patientName: 'Sophia Davis',
    appointmentId: 'apt-4',
    appointmentDate: '2026-03-30',
    appointmentTime: '14:00',
    type: 'EMAIL',
    messageContent: 'Hi Sophia Davis, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 2:00 PM | Provider: Dr. Michael Torres | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'failed',
    errorMessage: 'SendGrid: bounce — email address invalid',
    sentAt: '2026-03-29T14:00:00Z',
    retryCount: 3,
    ruleId: 'rule-2',
  },
  // ── Oliver Wilson (pat-5), apt-5: Dental Implant 2026-03-30 10:00 with Dr. Emily White ──
  {
    id: 'notif-12',
    patientId: 'pat-5',
    patientName: 'Oliver Wilson',
    appointmentId: 'apt-5',
    appointmentDate: '2026-03-30',
    appointmentTime: '10:00',
    type: 'EMAIL',
    messageContent: 'Hi Oliver Wilson, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 10:00 AM | Provider: Dr. Emily White | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'delivered',
    providerResponseId: 'sg-msg-00012',
    sentAt: '2026-03-27T10:00:00Z',
    deliveredAt: '2026-03-27T10:00:14Z',
    retryCount: 0,
    ruleId: 'rule-1',
  },
  {
    id: 'notif-13',
    patientId: 'pat-5',
    patientName: 'Oliver Wilson',
    appointmentId: 'apt-5',
    appointmentDate: '2026-03-30',
    appointmentTime: '10:00',
    type: 'SMS',
    messageContent: 'Hi Oliver Wilson! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 10:00 AM with Dr. Emily White. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'delivered',
    providerResponseId: 'SM00013mmnnoopp',
    sentAt: '2026-03-29T10:00:00Z',
    deliveredAt: '2026-03-29T10:00:27Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  // ── Ava Martinez (pat-6), apt-6: Orthodontic Consultation 2026-03-30 13:00 ──
  {
    id: 'notif-14',
    patientId: 'pat-6',
    patientName: 'Ava Martinez',
    appointmentId: 'apt-6',
    appointmentDate: '2026-03-30',
    appointmentTime: '13:00',
    type: 'SMS',
    messageContent: 'Hi Ava Martinez! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 1:00 PM with Dr. James Park. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'opted_out',
    sentAt: '2026-03-29T13:00:00Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  {
    id: 'notif-15',
    patientId: 'pat-6',
    patientName: 'Ava Martinez',
    appointmentId: 'apt-6',
    appointmentDate: '2026-03-30',
    appointmentTime: '13:00',
    type: 'EMAIL',
    messageContent: 'Hi Ava Martinez, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 1:00 PM | Provider: Dr. James Park | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'opted_out',
    sentAt: '2026-03-29T13:00:00Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  // ── William Garcia (pat-7), apt-7: Composite Filling 2026-03-30 15:30 with Dr. Emily White ──
  {
    id: 'notif-16',
    patientId: 'pat-7',
    patientName: 'William Garcia',
    appointmentId: 'apt-7',
    appointmentDate: '2026-03-30',
    appointmentTime: '15:30',
    type: 'SMS',
    messageContent: 'Hi William Garcia! This is a reminder from Air Dental that you have an appointment on Monday, March 30, 2026 at 3:30 PM with Dr. Emily White. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'sent',
    providerResponseId: 'SM00016qqrrsstt',
    sentAt: '2026-03-29T15:30:00Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  {
    id: 'notif-17',
    patientId: 'pat-7',
    patientName: 'William Garcia',
    appointmentId: 'apt-7',
    appointmentDate: '2026-03-30',
    appointmentTime: '15:30',
    type: 'EMAIL',
    messageContent: 'Hi William Garcia, This is a friendly reminder of your upcoming appointment: Date: Monday, March 30, 2026 | Time: 3:30 PM | Provider: Dr. Emily White | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'sent',
    providerResponseId: 'sg-msg-00017',
    sentAt: '2026-03-29T15:30:00Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  // ── Liam Thompson (pat-8), apt-8: Periodic Exam 2026-03-29 10:00 with Dr. Sarah Chen ──
  {
    id: 'notif-18',
    patientId: 'pat-8',
    patientName: 'Liam Thompson',
    appointmentId: 'apt-8',
    appointmentDate: '2026-03-29',
    appointmentTime: '10:00',
    type: 'SMS',
    messageContent: 'Hi Liam Thompson! This is a reminder from Air Dental that you have an appointment on Sunday, March 29, 2026 at 10:00 AM with Dr. Sarah Chen. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'delivered',
    providerResponseId: 'SM00018uuvvwwxx',
    sentAt: '2026-03-28T10:00:00Z',
    deliveredAt: '2026-03-28T10:00:16Z',
    retryCount: 0,
    ruleId: 'rule-2',
  },
  // ── Mia Anderson (pat-9), apt-9: Scaling & Root Planing 2026-03-31 09:00 with Dr. Michael Torres ──
  {
    id: 'notif-19',
    patientId: 'pat-9',
    patientName: 'Mia Anderson',
    appointmentId: 'apt-9',
    appointmentDate: '2026-03-31',
    appointmentTime: '09:00',
    type: 'EMAIL',
    messageContent: 'Hi Mia Anderson, This is a friendly reminder of your upcoming appointment: Date: Tuesday, March 31, 2026 | Time: 9:00 AM | Provider: Dr. Michael Torres | Location: Air Dental. Questions? Call us at (617) 555-0100.',
    status: 'queued',
    retryCount: 0,
    ruleId: 'rule-1',
  },
  {
    id: 'notif-20',
    patientId: 'pat-9',
    patientName: 'Mia Anderson',
    appointmentId: 'apt-9',
    appointmentDate: '2026-03-31',
    appointmentTime: '09:00',
    type: 'SMS',
    messageContent: 'Hi Mia Anderson! This is a reminder from Air Dental that you have an appointment on Tuesday, March 31, 2026 at 9:00 AM with Dr. Michael Torres. Questions? Call us at (617) 555-0100. Reply STOP to opt out.',
    status: 'queued',
    retryCount: 0,
    ruleId: 'rule-1',
  },
];
