// Mock staff / user accounts — updated with org chart hierarchy and account statuses.
// Per air_dental_staff_management_tab_spec.md.
// ⚠️ All names and credentials are fictional. Never use real staff data.

import type { StaffMember } from '../types/staff';

export const MOCK_STAFF: StaffMember[] = [
  // ── Practice Administration ──────────────────────────────────────────────
  {
    id:            'u-1',
    email:         'admin@airdental.com',
    firstName:     'Sarah',
    lastName:      'Chen',
    role:          'admin',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      true,
    lastLogin:     '2026-03-30T08:12:00Z',
    mfaEnabled:    true,
    createdAt:     '2025-01-01T00:00:00Z',
    locationIds:   ['loc-1', 'loc-2', 'loc-3'],
    providerId:    undefined,
    jobTitle:      'Practice Administrator',
    phone:         '4155550001',
    hireDate:      '2025-01-01',
    reportsTo:     undefined,               // Top of hierarchy
    accountStatus: 'active',
    department:    'management',
  },

  // ── Clinical — Main Office ────────────────────────────────────────────────
  {
    id:            'u-2',
    email:         'dr.torres@airdental.com',
    firstName:     'Michael',
    lastName:      'Torres',
    role:          'dentist',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      true,
    lastLogin:     '2026-03-30T07:55:00Z',
    mfaEnabled:    true,
    createdAt:     '2025-02-15T00:00:00Z',
    locationIds:   ['loc-1', 'loc-3'],
    providerId:    'prov-2',
    jobTitle:      'Endodontist',
    phone:         '4155550002',
    hireDate:      '2025-02-15',
    reportsTo:     'u-1',
    accountStatus: 'active',
    department:    'clinical',
  },
  {
    id:            'u-3',
    email:         'e.white@airdental.com',
    firstName:     'Emily',
    lastName:      'White',
    role:          'hygienist',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      true,
    lastLogin:     '2026-03-29T14:30:00Z',
    mfaEnabled:    true,
    createdAt:     '2025-03-01T00:00:00Z',
    locationIds:   ['loc-1'],
    providerId:    'prov-3',
    jobTitle:      'Dental Hygienist',
    phone:         '4155550003',
    hireDate:      '2025-03-01',
    reportsTo:     'u-2',                   // Reports to Dr. Torres
    accountStatus: 'active',
    department:    'clinical',
  },

  // ── Front Desk ───────────────────────────────────────────────────────────
  {
    id:            'u-4',
    email:         'j.park@airdental.com',
    firstName:     'James',
    lastName:      'Park',
    role:          'front_desk',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      true,
    lastLogin:     '2026-03-30T08:00:00Z',
    mfaEnabled:    false,
    createdAt:     '2025-04-01T00:00:00Z',
    locationIds:   ['loc-1'],
    providerId:    undefined,
    jobTitle:      'Front Desk Coordinator',
    phone:         '4155550004',
    hireDate:      '2025-04-01',
    reportsTo:     'u-1',
    accountStatus: 'active',
    department:    'front_desk',
  },
  {
    id:            'u-7',
    email:         's.adams@airdental.com',
    firstName:     'Sophia',
    lastName:      'Adams',
    role:          'front_desk',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      true,
    lastLogin:     '2026-03-30T08:05:00Z',
    mfaEnabled:    false,
    createdAt:     '2025-07-01T00:00:00Z',
    locationIds:   ['loc-2'],
    providerId:    undefined,
    jobTitle:      'Patient Coordinator',
    phone:         '4155550007',
    hireDate:      '2025-07-01',
    reportsTo:     'u-4',                   // Reports to James Park
    accountStatus: 'active',
    department:    'front_desk',
  },

  // ── Clinical — Downtown Office ────────────────────────────────────────────
  {
    id:            'u-5',
    email:         'dr.patel@airdental.com',
    firstName:     'Priya',
    lastName:      'Patel',
    role:          'dentist',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      true,
    lastLogin:     '2026-03-30T07:45:00Z',
    mfaEnabled:    true,
    createdAt:     '2025-06-01T00:00:00Z',
    locationIds:   ['loc-2'],
    providerId:    'prov-5',
    jobTitle:      'General Dentist',
    phone:         '4155550005',
    hireDate:      '2025-06-01',
    reportsTo:     'u-1',
    accountStatus: 'active',
    department:    'clinical',
  },

  // ── Clinical — Westside Office ────────────────────────────────────────────
  {
    id:            'u-6',
    email:         'dr.rivera@airdental.com',
    firstName:     'Carlos',
    lastName:      'Rivera',
    role:          'dentist',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      true,
    lastLogin:     '2026-03-28T16:00:00Z',
    mfaEnabled:    true,
    createdAt:     '2025-08-15T00:00:00Z',
    locationIds:   ['loc-3'],
    providerId:    'prov-6',
    jobTitle:      'General Dentist',
    phone:         '4155550006',
    hireDate:      '2025-08-15',
    reportsTo:     'u-1',
    accountStatus: 'active',
    department:    'clinical',
  },
  {
    id:            'u-8',
    email:         'o.foster@airdental.com',
    firstName:     'Olivia',
    lastName:      'Foster',
    role:          'hygienist',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      false,
    lastLogin:     '2026-02-14T09:00:00Z',
    mfaEnabled:    true,
    createdAt:     '2025-09-01T00:00:00Z',
    locationIds:   ['loc-3'],
    providerId:    undefined,
    jobTitle:      'Dental Hygienist',
    phone:         '4155550008',
    hireDate:      '2025-09-01',
    reportsTo:     'u-6',                   // Reports to Dr. Rivera
    accountStatus: 'deactivated',
    department:    'clinical',
  },

  // ── Invited / Pending (not yet active) ───────────────────────────────────
  {
    id:            'u-9',
    email:         'new.hire@airdental.com',
    firstName:     'Jordan',
    lastName:      'Lee',
    role:          'hygienist',
    clinicId:      'clinic-1',
    clinicName:    'Inspire Dental',
    isActive:      false,
    lastLogin:     null,
    mfaEnabled:    false,
    createdAt:     '2026-03-28T00:00:00Z',
    locationIds:   ['loc-1'],
    providerId:    undefined,
    jobTitle:      'Dental Hygienist',
    phone:         undefined,
    hireDate:      '2026-04-01',
    reportsTo:     'u-2',
    accountStatus: 'invited',
    department:    'clinical',
  },
];

export const MOCK_STAFF_MAP: Record<string, StaffMember> =
  Object.fromEntries(MOCK_STAFF.map(s => [s.id, s]));
