// Mock patient records — Phase 4 Patient Chart module.
// All names, addresses, and IDs are fictional. Never use real patient data.
// ⚠️ HIPAA: In production, patient data is PHI and must only be fetched server-side with audit logging.

import type { Patient } from '../types/patient';

export const MOCK_PATIENTS: Patient[] = [
  // ── pat-1: John Smith ─────────────────────────────────────────────────────
  {
    id: 'pat-1',
    chartNumber: '00001',
    firstName: 'John',
    lastName: 'Smith',
    dateOfBirth: '1985-04-12',
    gender: 'male',
    phone: '+1(617)423-8801',
    email: 'john.smith@email.com',
    address: {
      street: '142 Beacon St',
      city: 'Boston',
      state: 'MA',
      zip: '02116',
    },
    emergencyContact: {
      name: 'Mary Smith',
      relationship: 'Spouse',
      phone: '+1(617)423-8802',
    },
    allergies: [
      { substance: 'Penicillin', reaction: 'Anaphylaxis', severity: 'severe' },
    ],
    medications: [
      { name: 'Lisinopril', dose: '10mg daily', notes: 'For hypertension management' },
    ],
    medicalConditions: [
      { name: 'Hypertension', since: '2018' },
    ],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'Delta Dental PPO',
      groupNumber: 'GRP-44821',
      memberId: 'DDL-882134',
      groupName: 'Smith Enterprises Group',
      subscriberName: 'John Smith',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 87500,
      deductible: 5000,
      deductibleMet: 5000,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    balance: 42500,
    billingAlert: 'Chronic overdue balance — referred to collections',
    transactions: [
      { id: 'txn-1-1', date: '2025-06-15', type: 'charge',            description: 'Crown Preparation (D2710)',       amount: 85000,  balance: 85000,  providerId: 'prov-1' },
      { id: 'txn-1-2', date: '2025-06-20', type: 'insurance_payment', description: 'Delta Dental PPO Payment',        amount: -42500, balance: 42500,  providerId: 'prov-1' },
      { id: 'txn-1-3', date: '2025-09-10', type: 'charge',            description: 'Periodic Exam (D0120)',           amount: 15000,  balance: 57500,  providerId: 'prov-1' },
      { id: 'txn-1-4', date: '2025-09-10', type: 'insurance_payment', description: 'Delta Dental PPO Payment',        amount: -15000, balance: 42500,  providerId: 'prov-1' },
      { id: 'txn-1-5', date: '2025-12-01', type: 'charge',            description: 'Collection Notice Sent',          amount: 0,      balance: 42500,  providerId: 'prov-1' },
    ],
    status: 'active',
    firstVisit: '2020-03-15',
    lastVisit: '2026-03-30',
    preferredProviderId: 'prov-1',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-2: Emma Johnson ───────────────────────────────────────────────────
  {
    id: 'pat-2',
    chartNumber: '00002',
    firstName: 'Emma',
    lastName: 'Johnson',
    dateOfBirth: '1990-08-23',
    gender: 'female',
    phone: '+1(781)554-2247',
    email: 'emma.johnson@email.com',
    address: {
      street: '78 Hampshire St',
      city: 'Cambridge',
      state: 'MA',
      zip: '02139',
    },
    emergencyContact: {
      name: 'Robert Johnson',
      relationship: 'Father',
      phone: '+1(781)554-2248',
    },
    allergies: [],
    medications: [],
    medicalConditions: [],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'Aetna Dental',
      groupNumber: 'GRP-77234',
      memberId: 'AET-994521',
      groupName: 'Johnson & Associates',
      subscriberName: 'Emma Johnson',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 10000,
      deductible: 5000,
      deductibleMet: 5000,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    balance: 0,
    transactions: [
      { id: 'txn-2-1', date: '2025-04-12', type: 'charge',            description: 'Routine Cleaning (D1110)',         amount: 15000, balance: 15000, providerId: 'prov-1' },
      { id: 'txn-2-2', date: '2025-04-12', type: 'insurance_payment', description: 'Aetna Dental Payment',             amount: -15000, balance: 0,    providerId: 'prov-1' },
      { id: 'txn-2-3', date: '2025-10-18', type: 'charge',            description: 'Bitewing X-Rays (D0274)',           amount: 8000,  balance: 8000,  providerId: 'prov-1' },
      { id: 'txn-2-4', date: '2025-10-18', type: 'insurance_payment', description: 'Aetna Dental Payment',             amount: -8000,  balance: 0,    providerId: 'prov-1' },
    ],
    status: 'active',
    firstVisit: '2021-04-12',
    lastVisit: '2026-03-30',
    preferredProviderId: 'prov-1',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-3: Michael Brown ──────────────────────────────────────────────────
  {
    id: 'pat-3',
    chartNumber: '00003',
    firstName: 'Michael',
    lastName: 'Brown',
    dateOfBirth: '1978-11-05',
    gender: 'male',
    phone: '+1(508)319-6630',
    email: 'michael.brown@email.com',
    address: {
      street: '33 Main St Apt 4B',
      city: 'Somerville',
      state: 'MA',
      zip: '02143',
    },
    emergencyContact: {
      name: 'Linda Brown',
      relationship: 'Spouse',
      phone: '+1(508)319-6631',
    },
    allergies: [
      { substance: 'Aspirin', reaction: 'Hives', severity: 'moderate' },
      { substance: 'Latex', reaction: 'Rash', severity: 'mild' },
    ],
    medications: [
      { name: 'Metformin', dose: '500mg twice daily', notes: 'Diabetes Type 2 management' },
      { name: 'Glipizide', dose: '5mg daily', notes: 'Blood sugar control' },
    ],
    medicalConditions: [
      { name: 'Diabetes Type 2', since: '2015' },
    ],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'BlueCross BlueShield Dental',
      groupNumber: 'GRP-33104',
      memberId: 'BCBS-776512',
      groupName: 'Brown Manufacturing',
      subscriberName: 'Michael Brown',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 65000,
      deductible: 5000,
      deductibleMet: 5000,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    balance: 12000,
    transactions: [
      { id: 'txn-3-1', date: '2025-05-20', type: 'charge',            description: 'Root Canal Therapy (D3330)',         amount: 120000, balance: 120000, providerId: 'prov-2' },
      { id: 'txn-3-2', date: '2025-05-25', type: 'insurance_payment', description: 'BCBS Dental Payment',                amount: -96000,  balance: 24000,  providerId: 'prov-2' },
      { id: 'txn-3-3', date: '2025-06-15', type: 'patient_payment',   description: 'Patient Payment — Check #4412',      amount: -12000, balance: 12000,  providerId: 'prov-2' },
      { id: 'txn-3-4', date: '2025-11-08', type: 'charge',            description: 'Routine Cleaning (D1110)',            amount: 15000,  balance: 27000,  providerId: 'prov-2' },
      { id: 'txn-3-5', date: '2025-11-08', type: 'insurance_payment', description: 'BCBS Dental Payment',                amount: -15000, balance: 12000,  providerId: 'prov-2' },
    ],
    status: 'active',
    firstVisit: '2020-08-22',
    lastVisit: '2026-03-30',
    preferredProviderId: 'prov-2',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-4: Sophia Davis ───────────────────────────────────────────────────
  {
    id: 'pat-4',
    chartNumber: '00004',
    firstName: 'Sophia',
    lastName: 'Davis',
    dateOfBirth: '1995-02-17',
    gender: 'female',
    phone: '+1(617)887-4412',
    email: 'sophia.davis@email.com',
    address: {
      street: '210 Newbury St',
      city: 'Boston',
      state: 'MA',
      zip: '02116',
    },
    emergencyContact: {
      name: 'Patricia Davis',
      relationship: 'Mother',
      phone: '+1(617)887-4413',
    },
    allergies: [],
    medications: [
      { name: 'Sertraline', dose: '50mg daily', notes: 'Anxiety management' },
    ],
    medicalConditions: [
      { name: 'Anxiety', since: '2019' },
    ],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'Guardian Dental',
      groupNumber: 'GRP-55901',
      memberId: 'GRD-441228',
      groupName: 'Davis Tech Group',
      subscriberName: 'Sophia Davis',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 25000,
      deductible: 5000,
      deductibleMet: 5000,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    balance: 0,
    transactions: [
      { id: 'txn-4-1', date: '2025-07-14', type: 'charge',            description: 'Teeth Whitening (D9972)',           amount: 50000, balance: 50000, providerId: 'prov-2' },
      { id: 'txn-4-2', date: '2025-07-14', type: 'insurance_payment', description: 'Guardian Dental Payment',           amount: -25000, balance: 25000, providerId: 'prov-2' },
      { id: 'txn-4-3', date: '2025-07-20', type: 'patient_payment',   description: 'Patient Payment — Credit Card',      amount: -25000, balance: 0,     providerId: 'prov-2' },
      { id: 'txn-4-4', date: '2025-12-05', type: 'charge',            description: 'Routine Cleaning (D1110)',           amount: 15000, balance: 15000, providerId: 'prov-1' },
      { id: 'txn-4-5', date: '2025-12-05', type: 'insurance_payment', description: 'Guardian Dental Payment',           amount: -15000, balance: 0,     providerId: 'prov-1' },
    ],
    status: 'active',
    firstVisit: '2021-07-14',
    lastVisit: '2026-03-30',
    preferredProviderId: 'prov-1',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-5: Oliver Wilson ──────────────────────────────────────────────────
  {
    id: 'pat-5',
    chartNumber: '00005',
    firstName: 'Oliver',
    lastName: 'Wilson',
    dateOfBirth: '1982-07-30',
    gender: 'male',
    phone: '+1(339)204-7758',
    email: 'oliver.wilson@email.com',
    address: {
      street: '55 Tremont St Apt 12',
      city: 'Boston',
      state: 'MA',
      zip: '02108',
    },
    emergencyContact: {
      name: 'Catherine Wilson',
      relationship: 'Spouse',
      phone: '+1(339)204-7759',
    },
    allergies: [
      { substance: 'Amoxicillin', reaction: 'Anaphylaxis', severity: 'severe' },
    ],
    medications: [
      { name: 'Warfarin', dose: '5mg daily', notes: 'Anticoagulant — inform before any surgical procedure' },
    ],
    medicalConditions: [
      { name: 'Blood thinners (Warfarin)', since: '2017' },
    ],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'MetLife Dental',
      groupNumber: 'GRP-66012',
      memberId: 'MET-223345',
      groupName: 'Wilson Financial Corp',
      subscriberName: 'Oliver Wilson',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 120000,
      deductible: 5000,
      deductibleMet: 5000,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    secondaryInsurance: {
      type: 'ppo',
      carrier: 'UnitedHealthcare Dental',
      groupNumber: 'GRP-88234',
      memberId: 'UHC-551201',
      groupName: 'Wilson Financial Supplemental',
      subscriberName: 'Oliver Wilson',
      relationship: 'self',
      annualMax: 100000,
      annualMaxUsed: 22000,
      deductible: 0,
      deductibleMet: 0,
      preventiveCoverage: 100,
      basicCoverage: 50,
      majorCoverage: 25,
    },
    balance: 78000,
    billingAlert: 'High balance — payment plan required',
    transactions: [
      { id: 'txn-5-1', date: '2025-08-10', type: 'charge',            description: 'Dental Implant (D6010)',              amount: 350000, balance: 350000, providerId: 'prov-3' },
      { id: 'txn-5-2', date: '2025-08-20', type: 'insurance_payment', description: 'MetLife Dental Payment',              amount: -150000, balance: 200000, providerId: 'prov-3' },
      { id: 'txn-5-3', date: '2025-08-20', type: 'insurance_payment', description: 'UnitedHealthcare Dental Payment',      amount: -100000, balance: 100000, providerId: 'prov-3' },
      { id: 'txn-5-4', date: '2025-10-01', type: 'patient_payment',   description: 'Payment Plan — Installment 1',         amount: -15000, balance: 85000,  providerId: 'prov-3' },
      { id: 'txn-5-5', date: '2025-11-01', type: 'patient_payment',   description: 'Payment Plan — Installment 2',         amount: -7000,  balance: 78000,  providerId: 'prov-3' },
    ],
    status: 'active',
    firstVisit: '2020-02-10',
    lastVisit: '2026-03-30',
    preferredProviderId: 'prov-3',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-6: Ava Martinez ───────────────────────────────────────────────────
  {
    id: 'pat-6',
    chartNumber: '00006',
    firstName: 'Ava',
    lastName: 'Martinez',
    dateOfBirth: '2008-12-01',
    gender: 'female',
    phone: '+1(617)645-0933',
    email: 'ava.martinez@email.com',
    address: {
      street: '19 Highland Ave',
      city: 'Somerville',
      state: 'MA',
      zip: '02144',
    },
    emergencyContact: {
      name: 'Carlos Martinez',
      relationship: 'Father',
      phone: '+1(617)645-0934',
    },
    allergies: [],
    medications: [],
    medicalConditions: [],
    primaryInsurance: {
      type: 'medicaid',
      carrier: 'MassHealth Dental',
      groupNumber: 'MH-0001',
      memberId: 'MH-88441201',
      groupName: 'MassHealth',
      subscriberName: 'Ava Martinez',
      relationship: 'self',
      annualMax: 0,
      annualMaxUsed: 0,
      deductible: 0,
      deductibleMet: 0,
      preventiveCoverage: 100,
      basicCoverage: 100,
      majorCoverage: 100,
    },
    balance: 0,
    transactions: [
      { id: 'txn-6-1', date: '2025-09-05', type: 'charge',            description: 'Orthodontic Consultation (D8660)',   amount: 20000, balance: 20000, providerId: 'prov-4' },
      { id: 'txn-6-2', date: '2025-09-05', type: 'insurance_payment', description: 'MassHealth Payment',                amount: -20000, balance: 0,     providerId: 'prov-4' },
      { id: 'txn-6-3', date: '2026-01-10', type: 'charge',            description: 'Routine Cleaning (D1120)',           amount: 12000, balance: 12000, providerId: 'prov-4' },
      { id: 'txn-6-4', date: '2026-01-10', type: 'insurance_payment', description: 'MassHealth Payment',                amount: -12000, balance: 0,     providerId: 'prov-4' },
    ],
    status: 'active',
    firstVisit: '2022-09-05',
    lastVisit: '2026-03-30',
    preferredProviderId: 'prov-4',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-7: William Garcia ─────────────────────────────────────────────────
  {
    id: 'pat-7',
    chartNumber: '00007',
    firstName: 'William',
    lastName: 'Garcia',
    dateOfBirth: '1970-03-22',
    gender: 'male',
    phone: '+1(781)762-5521',
    email: 'william.garcia@email.com',
    address: {
      street: '5 Elm Court',
      city: 'Newton',
      state: 'MA',
      zip: '02458',
    },
    emergencyContact: {
      name: 'Sandra Garcia',
      relationship: 'Spouse',
      phone: '+1(781)762-5522',
    },
    allergies: [
      { substance: 'Codeine', reaction: 'Nausea and vomiting', severity: 'moderate' },
    ],
    medications: [
      { name: 'Levothyroxine', dose: '75mcg daily', notes: 'Thyroid hormone replacement' },
    ],
    medicalConditions: [
      { name: 'Thyroid disorder', since: '2012' },
    ],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'UnitedHealthcare Dental',
      groupNumber: 'GRP-99123',
      memberId: 'UHC-771432',
      groupName: 'Garcia Legal Group',
      subscriberName: 'William Garcia',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 90000,
      deductible: 5000,
      deductibleMet: 5000,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    balance: 5500,
    transactions: [
      { id: 'txn-7-1', date: '2025-07-22', type: 'charge',            description: 'Composite Filling x2 (D2391)',        amount: 40000, balance: 40000, providerId: 'prov-3' },
      { id: 'txn-7-2', date: '2025-07-30', type: 'insurance_payment', description: 'UHC Dental Payment',                  amount: -32000, balance: 8000,  providerId: 'prov-3' },
      { id: 'txn-7-3', date: '2025-08-15', type: 'patient_payment',   description: 'Patient Payment — Cash',               amount: -2500, balance: 5500,  providerId: 'prov-3' },
      { id: 'txn-7-4', date: '2025-12-12', type: 'charge',            description: 'Periodic Exam (D0120)',                amount: 10000, balance: 15500, providerId: 'prov-3' },
      { id: 'txn-7-5', date: '2025-12-12', type: 'insurance_payment', description: 'UHC Dental Payment',                  amount: -10000, balance: 5500,  providerId: 'prov-3' },
    ],
    status: 'active',
    firstVisit: '2020-07-22',
    lastVisit: '2026-03-30',
    preferredProviderId: 'prov-1',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-8: Liam Thompson ──────────────────────────────────────────────────
  {
    id: 'pat-8',
    chartNumber: '00008',
    firstName: 'Liam',
    lastName: 'Thompson',
    dateOfBirth: '1999-06-14',
    gender: 'male',
    phone: '+1(857)341-9004',
    email: 'liam.thompson@email.com',
    address: {
      street: '88 Prospect St',
      city: 'Cambridge',
      state: 'MA',
      zip: '02139',
    },
    emergencyContact: {
      name: 'James Thompson',
      relationship: 'Father',
      phone: '+1(857)341-9005',
    },
    allergies: [],
    medications: [],
    medicalConditions: [],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'Aetna Dental',
      groupNumber: 'GRP-11445',
      memberId: 'AET-332201',
      groupName: 'Thompson Corp',
      subscriberName: 'Liam Thompson',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 0,
      deductible: 5000,
      deductibleMet: 0,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    balance: 0,
    transactions: [
      { id: 'txn-8-1', date: '2026-03-29', type: 'charge',            description: 'Periodic Exam — New Patient (D0150)', amount: 18000, balance: 18000, providerId: 'prov-1' },
      { id: 'txn-8-2', date: '2026-03-29', type: 'insurance_payment', description: 'Aetna Dental Payment',                amount: -18000, balance: 0,    providerId: 'prov-1' },
    ],
    status: 'new',
    firstVisit: '2026-03-29',
    lastVisit: '2026-03-29',
    preferredProviderId: 'prov-1',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },

  // ── pat-9: Mia Anderson ───────────────────────────────────────────────────
  {
    id: 'pat-9',
    chartNumber: '00009',
    firstName: 'Mia',
    lastName: 'Anderson',
    dateOfBirth: '1988-09-08',
    gender: 'female',
    phone: '+1(617)290-8816',
    email: 'mia.anderson@email.com',
    address: {
      street: '301 Washington St Apt 5',
      city: 'Brighton',
      state: 'MA',
      zip: '02135',
    },
    emergencyContact: {
      name: 'Peter Anderson',
      relationship: 'Spouse',
      phone: '+1(617)290-8817',
    },
    allergies: [
      { substance: 'Sulfa', reaction: 'Bronchospasm', severity: 'moderate' },
    ],
    medications: [
      { name: 'Albuterol inhaler', dose: '2 puffs as needed', notes: 'Rescue inhaler for asthma attacks' },
    ],
    medicalConditions: [
      { name: 'Asthma', since: '2003' },
    ],
    primaryInsurance: {
      type: 'ppo',
      carrier: 'Guardian Dental',
      groupNumber: 'GRP-22810',
      memberId: 'GRD-887654',
      groupName: 'Anderson Media Inc',
      subscriberName: 'Mia Anderson',
      relationship: 'self',
      annualMax: 150000,
      annualMaxUsed: 45000,
      deductible: 5000,
      deductibleMet: 5000,
      preventiveCoverage: 100,
      basicCoverage: 80,
      majorCoverage: 50,
    },
    balance: 9000,
    transactions: [
      { id: 'txn-9-1', date: '2025-05-15', type: 'charge',            description: 'Scaling & Root Planing (D4341)',     amount: 80000,  balance: 80000,  providerId: 'prov-2' },
      { id: 'txn-9-2', date: '2025-05-22', type: 'insurance_payment', description: 'Guardian Dental Payment',           amount: -64000,  balance: 16000,  providerId: 'prov-2' },
      { id: 'txn-9-3', date: '2025-06-10', type: 'patient_payment',   description: 'Patient Payment — Debit Card',       amount: -7000,   balance: 9000,   providerId: 'prov-2' },
      { id: 'txn-9-4', date: '2025-11-20', type: 'charge',            description: 'Routine Cleaning (D1110)',           amount: 15000,  balance: 24000,  providerId: 'prov-2' },
      { id: 'txn-9-5', date: '2025-11-20', type: 'insurance_payment', description: 'Guardian Dental Payment',           amount: -15000,  balance: 9000,   providerId: 'prov-2' },
    ],
    status: 'active',
    firstVisit: '2021-05-15',
    lastVisit: '2026-03-31',
    preferredProviderId: 'prov-1',
    clinicId: 'clinic-1',
    locationId: 'loc-1',
  },
];

// O(1) patient lookup by ID
export const MOCK_PATIENTS_MAP: Record<string, Patient> = Object.fromEntries(
  MOCK_PATIENTS.map(p => [p.id, p]),
);
